package tienda;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Tienda extends javax.swing.JFrame implements Runnable{
    
    public Tienda() {
        initComponents();
        lblProtectorPantalla.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmNvProducto = new javax.swing.JFrame();
        frmNvTarjeta = new javax.swing.JFrame();
        lblProtectorPantalla = new javax.swing.JLabel();

        javax.swing.GroupLayout frmNvProductoLayout = new javax.swing.GroupLayout(frmNvProducto.getContentPane());
        frmNvProducto.getContentPane().setLayout(frmNvProductoLayout);
        frmNvProductoLayout.setHorizontalGroup(
            frmNvProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        frmNvProductoLayout.setVerticalGroup(
            frmNvProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout frmNvTarjetaLayout = new javax.swing.GroupLayout(frmNvTarjeta.getContentPane());
        frmNvTarjeta.getContentPane().setLayout(frmNvTarjetaLayout);
        frmNvTarjetaLayout.setHorizontalGroup(
            frmNvTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        frmNvTarjetaLayout.setVerticalGroup(
            frmNvTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProtectorPantalla.setText("Tarjeta Encontrada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(lblProtectorPantalla)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(lblProtectorPantalla)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       Tienda tienda = new Tienda();
       tienda.setVisible(true);
       tienda.run();
    }
    
    public void run() {
        try
        {
            System.out.println("Main thread");
            boolean fileFound = false;
            while(fileFound == false){
                
                Thread.sleep(2000);

                File[] paths = File.listRoots();

                for(File path:paths) {
                    File tarjeta = new File(path.toString() + "/Tarjeta","Tarjeta.dmc");

                    if(tarjeta.exists()) {
                        System.out.println("Tajeta Encontrada");
                        
                        if(Controlador.tarjetaValida(tarjeta)) {
                            fileFound = true;
                            System.out.println("Tarjeta Valida");
                            break;
                        }
                        else
                            System.out.println("Tarjeta No Valida");
                    }
                    else {
                        System.out.println("Tarjeta No Encontrada");
                    }
                }
            }
            
            lblProtectorPantalla.setVisible(true);

        } catch (InterruptedException ex) {
            Logger.getLogger(Tienda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame frmNvProducto;
    private javax.swing.JFrame frmNvTarjeta;
    private javax.swing.JLabel lblProtectorPantalla;
    // End of variables declaration//GEN-END:variables
}
